/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPurchaseRouteImport } from './routes/user/purchase'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as UserPurchaseIndexRouteImport } from './routes/user/purchase/index'
import { Route as UserPurchaseOrderIdRouteImport } from './routes/user/purchase/$orderId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPurchaseRoute = UserPurchaseRouteImport.update({
  id: '/user/purchase',
  path: '/user/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPurchaseIndexRoute = UserPurchaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserPurchaseRoute,
} as any)
const UserPurchaseOrderIdRoute = UserPurchaseOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => UserPurchaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/user/purchase': typeof UserPurchaseRouteWithChildren
  '/user/purchase/$orderId': typeof UserPurchaseOrderIdRoute
  '/user/purchase/': typeof UserPurchaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/user/purchase/$orderId': typeof UserPurchaseOrderIdRoute
  '/user/purchase': typeof UserPurchaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/user/purchase': typeof UserPurchaseRouteWithChildren
  '/user/purchase/$orderId': typeof UserPurchaseOrderIdRoute
  '/user/purchase/': typeof UserPurchaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/signin'
    | '/signup'
    | '/categories/$slug'
    | '/products/$productId'
    | '/user/purchase'
    | '/user/purchase/$orderId'
    | '/user/purchase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/signin'
    | '/signup'
    | '/categories/$slug'
    | '/products/$productId'
    | '/user/purchase/$orderId'
    | '/user/purchase'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/signin'
    | '/signup'
    | '/categories/$slug'
    | '/products/$productId'
    | '/user/purchase'
    | '/user/purchase/$orderId'
    | '/user/purchase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  UserPurchaseRoute: typeof UserPurchaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/purchase': {
      id: '/user/purchase'
      path: '/user/purchase'
      fullPath: '/user/purchase'
      preLoaderRoute: typeof UserPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/purchase/': {
      id: '/user/purchase/'
      path: '/'
      fullPath: '/user/purchase/'
      preLoaderRoute: typeof UserPurchaseIndexRouteImport
      parentRoute: typeof UserPurchaseRoute
    }
    '/user/purchase/$orderId': {
      id: '/user/purchase/$orderId'
      path: '/$orderId'
      fullPath: '/user/purchase/$orderId'
      preLoaderRoute: typeof UserPurchaseOrderIdRouteImport
      parentRoute: typeof UserPurchaseRoute
    }
  }
}

interface UserPurchaseRouteChildren {
  UserPurchaseOrderIdRoute: typeof UserPurchaseOrderIdRoute
  UserPurchaseIndexRoute: typeof UserPurchaseIndexRoute
}

const UserPurchaseRouteChildren: UserPurchaseRouteChildren = {
  UserPurchaseOrderIdRoute: UserPurchaseOrderIdRoute,
  UserPurchaseIndexRoute: UserPurchaseIndexRoute,
}

const UserPurchaseRouteWithChildren = UserPurchaseRoute._addFileChildren(
  UserPurchaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  UserPurchaseRoute: UserPurchaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
